import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Banner from "../components/Banner";

import LargeButton from "../components/LargeButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>We Are Crew</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-[96px]">
        <Banner />
      </div>

      <div className=" h-[calc(100vh-296px)] flex w-full justify-around items-center">
        <LargeButton text="I need crew" link="/I-need-crew/depts" />
        <LargeButton text="I am crew" link="/I-am-crew" />
      </div>
    </div>
  );
}
