import Head from 'next/head'
import styles from '../styles/Home.module.css'

import LargeButton from '../components/LargeButton';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>We Are Crew</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to We Are Crew
        </h1>
        
        <div className='flex justify-around w-full mt-12'>
          <LargeButton text='I need crew' link='/i-need-crew'/>
          <LargeButton text='I am crew' link='/i-am-crew'/>
        </div>
      </main>

      
    </div>
  )
}
